function [temperature,totalHorizontal,beamNormal,diffuseHorizontal,offsetGMT] = importWeather(fileName,t)
% importWeather imports and processes weather data from a CSV file
% generated by OikoLab.
%
% Input:
%   fileName, the name of the OikoLab CSV weather file.
%   t, the datetime span.
%
% Output:
%   temperature, the outdoor temperature in C
%   totalHorizontal, the total solar shortwave irradiance on a horizontal surface in kW/m^2
%   beamNormal, the beam solar shortwave irradiance on a normal surface in kW/m^2
%   diffuseHorizontal, the diffuse solar shortwave irradiance on a horizontal surface in kW/m^2
%   offsetGMT, (local time) - (Greenwich mean time) in hours

% import raw data
opts = detectImportOptions(fileName);
opts.PreserveVariableNames = 1;
weatherData = readtable(fileName,opts);

% extract data and convert units
timeStamp = weatherData{:,1}; % time stamp
if timeStamp(1).Year < 2000, timeStamp.Year = timeStamp.Year + 2000; end
offsetGMT = weatherData{:,5};
timeStamp = timeStamp + hours(offsetGMT); % convert UTC to eastern
temperature = weatherData{:,6}; % outdoor air temperature, C
totalHorizontal = weatherData{:,7}/1000; % total horizontal shortwave irradiance, kW/m^2
beamNormal = weatherData{:,8}/1000; % beam normal shortwave irradiance, kW/m^2
diffuseHorizontal = weatherData{:,9}/1000; % diffuse horizontal shortwave irradiance, kW/m^2

% fill any missing data
temperature = fillmissing(temperature,'linear');
totalHorizontal = fillmissing(totalHorizontal,'linear');
beamNormal = fillmissing(beamNormal,'linear');
diffuseHorizontal = fillmissing(diffuseHorizontal,'linear');

% pack the data into a timetable object
TT = timetable(timeStamp,...
    temperature,totalHorizontal,beamNormal,diffuseHorizontal,offsetGMT);

% retime to the desired time steps
TT = retime(TT,t);
temperature = TT{:,1};
totalHorizontal = TT{:,2};
beamNormal = TT{:,3};
diffuseHorizontal = TT{:,4};
offsetGMT = TT{:,5};

% fill any missing data again
temperature = fillmissing(temperature,'linear');
totalHorizontal = fillmissing(totalHorizontal,'linear');
beamNormal = fillmissing(beamNormal,'linear');
diffuseHorizontal = fillmissing(diffuseHorizontal,'linear');
offsetGMT = fillmissing(offsetGMT,'linear');

end

